name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: node setup
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      # there is an issue with user the lastest version of web-ext to build
      # https://discourse.mozilla.org/t/webexterror-unsupported-filetype-when-trying-to-sign-a-locally-built-extension/143055
      - name: build tool installation
        run: npm install -g web-ext@8.2.0

      - name: build and sign
        run: web-ext sign --channel=unlisted --api-key=${{ secrets.AMO_JWT_ISSUER }} --api-secret=${{ secrets.AMO_JWT_SECRET }}

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: web-ext-artifacts/*.xpi
